### PR TITLE
Fix for the ReDOS vulnerability

### PR DESCRIPTION
**Pull request by snyk-community**
ant-ux is currently affected by the high-severity [ReDOS vulnerability](https://snyk.io/vuln/npm:negotiator:20160616). 

Vulnerable module: `negotiator`
Introduced through: `express`

This PR fixes the ReDOS vulnerability by upgrading `express` to version 4.0.0

Check out the [Snyk test report](https://snyk.io/test/github/ant-design/ant-ux) to review other vulnerabilities that affect this repo. 

[Watch the repo](https://snyk.io/add) to 
- get alerts if newly disclosed vulnerabilities affect this repo in the future. 
- generate pull requests with the fixes you want, or let us do the work: when a newly disclosed vulnerability affects you, we'll submit a fix to you right away. 

Stay secure, 
The Snyk team

### CODE REVIEW

**Comment by benjycui** [comment]
ant-ux is just a static website.... Why do you need `express` @hi-caicai

**Comment by hi-caicai** [comment]
@benjycui Because I want to test the page in the local environment...

**Comment by benjycui** [comment]
Just use [dora](https://github.com/dora-js/dora).

**Comment by hi-caicai** [comment]
@benjycui 🐒

**Pull request merged**
